import Mathlib.Data.Multiset.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.Circle

/-!
# Root selection for conjugation/inversion-closed multisets (Fejér–Riesz core)

This module proves the purely combinatorial root-selection core of the Fejér–Riesz
factorisation: a finite multiset `S : Multiset ℂ` that avoids `0`, is closed under
both complex conjugation and inversion `(·⁻¹)`, and whose real-or-unit-circle part is
exactly `{-1, -1}`, splits as `S = S₀ + S₀.map (starRingEnd ℂ)` for some
inversion-closed `S₀`. Downstream (`ComplementRoots.lean`) this is applied to
`(qtilde P).roots` to extract the spectral half giving the factor `R` with
`R · R̄ = q̃`.

The proof is a strong induction on `Multiset.card S`. Off the two axes, roots occur in
distinct quadruples `{ζ, ζ̄, ζ⁻¹, ζ̄⁻¹}`; we peel one quadruple, assigning `{ζ, ζ⁻¹}` to
`S₀` and `{ζ̄, ζ̄⁻¹}` to `S₀.map conj`, and recurse on the (still-closed, still
real-or-circle-part-`{-1,-1}`) residue. The base case `S = {-1, -1}` takes `S₀ = {-1}`.

## Main statement
- `exists_conj_split` — the decomposition (frozen interface for `ComplementRoots.lean`).
-/

namespace QAOA.IsingChain.Achievability

/-- The predicate selecting real-or-unit-circle elements. -/
private def AxisP (ζ : ℂ) := ζ.im = 0 ∨ ‖ζ‖ = 1

/-! ### Off-axis distinctness facts -/

/-- An off-axis element is nonzero. -/
private theorem ne_zero_of_offAxis {ζ : ℂ} (hoff : ¬ AxisP ζ) : ζ ≠ 0 := by
  rintro rfl
  exact hoff (Or.inl (by simp))

/-- For an off-axis `ζ`, conjugation moves it: `ζ̄ ≠ ζ`. -/
private theorem conj_ne_self_of_offAxis {ζ : ℂ} (hoff : ¬ AxisP ζ) :
    (starRingEnd ℂ) ζ ≠ ζ := by
  rw [ne_eq, Complex.conj_eq_iff_im]
  exact fun h => hoff (Or.inl h)

/-- For an off-axis `ζ`, inversion moves it: `ζ⁻¹ ≠ ζ`. -/
private theorem inv_ne_self_of_offAxis {ζ : ℂ} (hoff : ¬ AxisP ζ) : ζ⁻¹ ≠ ζ := by
  have hζ0 : ζ ≠ 0 := ne_zero_of_offAxis hoff
  intro h
  have hmul : ζ * ζ = 1 := by
    field_simp at h; linear_combination -h
  rw [mul_self_eq_one_iff] at hmul
  rcases hmul with h1 | h1
  · exact hoff (Or.inr (by rw [h1]; simp))
  · exact hoff (Or.inr (by rw [h1]; simp))

/-- For an off-axis `ζ`, `(ζ̄)⁻¹ ≠ ζ` (else `‖ζ‖ = 1`). -/
private theorem conj_inv_ne_self_of_offAxis {ζ : ℂ} (hoff : ¬ AxisP ζ) :
    ((starRingEnd ℂ) ζ)⁻¹ ≠ ζ := by
  have hζ0 : ζ ≠ 0 := ne_zero_of_offAxis hoff
  intro h
  have hcz : (starRingEnd ℂ) ζ ≠ 0 := by simpa using hζ0
  have hmul : ζ * (starRingEnd ℂ) ζ = 1 := by
    field_simp at h; linear_combination -h
  rw [Complex.mul_conj] at hmul
  have hns : Complex.normSq ζ = 1 := by exact_mod_cast hmul
  rw [Complex.normSq_eq_norm_sq] at hns
  have : ‖ζ‖ = 1 := by nlinarith [norm_nonneg ζ]
  exact hoff (Or.inr this)

/-- Being off the two axes is preserved by conjugation. -/
private theorem offAxis_conj {ζ : ℂ} (hoff : ¬ AxisP ζ) : ¬ AxisP ((starRingEnd ℂ) ζ) := by
  simp only [AxisP, not_or] at hoff ⊢
  refine ⟨?_, ?_⟩
  · rw [Complex.conj_im]; simpa using hoff.1
  · rw [Complex.norm_conj]; exact hoff.2

/-- Being off the two axes is preserved by inversion. -/
private theorem offAxis_inv {ζ : ℂ} (hoff : ¬ AxisP ζ) : ¬ AxisP ζ⁻¹ := by
  have hζ0 : ζ ≠ 0 := ne_zero_of_offAxis hoff
  simp only [AxisP, not_or] at hoff ⊢
  refine ⟨?_, ?_⟩
  · rw [Complex.inv_im]
    intro h
    rw [div_eq_zero_iff] at h
    rcases h with h | h
    · exact hoff.1 (by simpa using h)
    · exact hζ0 (Complex.normSq_eq_zero.mp h)
  · rw [norm_inv]
    intro h
    have hpos : ‖ζ‖ ≠ 0 := norm_ne_zero_iff.mpr hζ0
    field_simp at h
    exact hoff.2 h.symm

/-! ### The off-axis quadruple `{ζ, ζ̄, ζ⁻¹, ζ̄⁻¹}` -/

/-- The conjugation/inversion-closed quadruple generated by `ζ`. -/
private noncomputable def quad (ζ : ℂ) : Multiset ℂ :=
  {ζ, (starRingEnd ℂ) ζ, ζ⁻¹, ((starRingEnd ℂ) ζ)⁻¹}

/-- `quad ζ` is conjugation-closed as a multiset. -/
private theorem quad_map_conj (ζ : ℂ) : (quad ζ).map (starRingEnd ℂ) = quad ζ := by
  unfold quad
  simp only [Multiset.insert_eq_cons, Multiset.map_cons, Multiset.map_singleton,
    Complex.conj_conj, map_inv₀]
  -- conj ζ ::ₘ ζ ::ₘ (conj ζ)⁻¹ ::ₘ {ζ⁻¹} = ζ ::ₘ conj ζ ::ₘ ζ⁻¹ ::ₘ {(conj ζ)⁻¹}
  rw [Multiset.cons_swap]
  congr 1
  rw [show ((starRingEnd ℂ) ζ)⁻¹ ::ₘ {ζ⁻¹} = ζ⁻¹ ::ₘ {((starRingEnd ℂ) ζ)⁻¹} from
    Multiset.cons_swap _ _ _]

/-- `quad ζ` is inversion-closed as a multiset. -/
private theorem quad_map_inv (ζ : ℂ) : (quad ζ).map (·⁻¹) = quad ζ := by
  unfold quad
  simp only [Multiset.insert_eq_cons, Multiset.map_cons, Multiset.map_singleton, inv_inv]
  -- ζ⁻¹ ::ₘ (conj ζ)⁻¹ ::ₘ ζ ::ₘ {conj ζ} = ζ ::ₘ conj ζ ::ₘ ζ⁻¹ ::ₘ {(conj ζ)⁻¹}
  -- use count-extensionality
  classical
  refine Multiset.ext.mpr (fun a => ?_)
  simp only [Multiset.count_cons, Multiset.count_singleton]
  ring

/-- Membership in `quad ζ`. -/
private theorem mem_quad {ζ a : ℂ} :
    a ∈ quad ζ ↔ a = ζ ∨ a = (starRingEnd ℂ) ζ ∨ a = ζ⁻¹ ∨ a = ((starRingEnd ℂ) ζ)⁻¹ := by
  unfold quad
  simp only [Multiset.insert_eq_cons, Multiset.mem_cons, Multiset.mem_singleton]

open Classical in
/-- Every element of an off-axis `quad ζ` is off the two axes. -/
private theorem quad_filter_eq_zero {ζ : ℂ} (hoff : ¬ AxisP ζ) :
    (quad ζ).filter AxisP = 0 := by
  rw [Multiset.filter_eq_nil]
  intro a ha
  rw [mem_quad] at ha
  rcases ha with rfl | rfl | rfl | rfl
  · exact hoff
  · exact offAxis_conj hoff
  · exact offAxis_inv hoff
  · exact offAxis_inv (offAxis_conj hoff)

/-- The four elements of an off-axis `quad ζ` are pairwise distinct. -/
private theorem quad_nodup {ζ : ℂ} (hoff : ¬ AxisP ζ) : (quad ζ).Nodup := by
  have e1 : (starRingEnd ℂ) ζ ≠ ζ := conj_ne_self_of_offAxis hoff
  have e2 : ζ⁻¹ ≠ ζ := inv_ne_self_of_offAxis hoff
  have e3 : ((starRingEnd ℂ) ζ)⁻¹ ≠ ζ := conj_inv_ne_self_of_offAxis hoff
  have e5 : ((starRingEnd ℂ) ζ)⁻¹ ≠ (starRingEnd ℂ) ζ :=
    inv_ne_self_of_offAxis (offAxis_conj hoff)
  have e4 : ζ⁻¹ ≠ (starRingEnd ℂ) ζ := by
    intro h; apply e3
    have := congrArg (·⁻¹) h
    simp only [inv_inv] at this; rw [← this]
  have e6 : ((starRingEnd ℂ) ζ)⁻¹ ≠ ζ⁻¹ := fun h => e1 (inv_injective h)
  unfold quad
  simp only [Multiset.insert_eq_cons, Multiset.nodup_cons, Multiset.mem_cons,
    Multiset.mem_singleton, Multiset.nodup_singleton, and_true, not_or]
  exact ⟨⟨e1.symm, e2.symm, e3.symm⟩, ⟨e4.symm, e5.symm⟩, e6.symm⟩

/-- If all four members of `quad ζ` lie in `S`, then `quad ζ ≤ S`. -/
private theorem quad_le {ζ : ℂ} {S : Multiset ℂ} (hoff : ¬ AxisP ζ)
    (hmem : ∀ a ∈ quad ζ, a ∈ S) : quad ζ ≤ S := by
  rw [Multiset.le_iff_subset (quad_nodup hoff)]
  exact fun a ha => hmem a ha

/-! ### The decomposition: count form -/

open Classical in
/-- **Decomposition lemma (count form).** A multiset `S` avoiding `0`, count-closed
under conjugation and inversion, whose real-or-circle part is `{-1, -1}`, splits as
`S = S₀ + S₀.map conj` for an inversion-closed `S₀`. The induction carries the closures
in count form (robust under `Multiset.sub`). -/
private theorem exists_conj_split_aux (S : Multiset ℂ)
    (h0 : (0 : ℂ) ∉ S)
    (hconj : ∀ ζ, S.count ((starRingEnd ℂ) ζ) = S.count ζ)
    (hinv : ∀ ζ, S.count ζ⁻¹ = S.count ζ)
    (hRC : S.filter AxisP = {(-1 : ℂ), -1}) :
    ∃ S₀ : Multiset ℂ, S₀.map (·⁻¹) = S₀ ∧ S = S₀ + S₀.map (starRingEnd ℂ) := by
  induction S using Multiset.strongInductionOn with
  | _ S ih =>
    by_cases hex : ∃ ζ ∈ S, ¬ AxisP ζ
    · -- Case YES: peel an off-axis quadruple.
      obtain ⟨ζ, hζS, hoff⟩ := hex
      -- (1) the four members of `quad ζ` lie in `S`.
      have hζc : 0 < S.count ζ := Multiset.count_pos.mpr hζS
      have hmem : ∀ a ∈ quad ζ, a ∈ S := by
        intro a ha
        rw [mem_quad] at ha
        rcases ha with rfl | rfl | rfl | rfl
        · exact hζS
        · rw [← Multiset.count_pos, hconj]; exact hζc
        · rw [← Multiset.count_pos, hinv]; exact hζc
        · rw [← Multiset.count_pos, hinv, hconj]; exact hζc
      have hqle : quad ζ ≤ S := quad_le hoff hmem
      -- (2) the residue `S' := S - quad ζ` is strictly smaller.
      have hqne : quad ζ ≠ 0 := by
        intro h
        exact Multiset.notMem_zero ζ (h ▸ mem_quad.mpr (Or.inl rfl))
      have hlt : S - quad ζ < S := by
        have h1 : S - quad ζ ≤ S := Multiset.sub_le_self S (quad ζ)
        rcases lt_or_eq_of_le h1 with h | h
        · exact h
        · exfalso
          have hc : (S - quad ζ).card = S.card := by rw [h]
          rw [Multiset.card_sub hqle] at hc
          have hcq : (quad ζ).card = 0 := by
            have := Multiset.card_le_card hqle; omega
          exact hqne (Multiset.card_eq_zero.mp hcq)
      -- (3) re-establish the hypotheses for `S'`.
      have hqconj : ∀ ξ, (quad ζ).count ((starRingEnd ℂ) ξ) = (quad ζ).count ξ := by
        intro ξ
        have key := Multiset.count_map_eq_count' (starRingEnd ℂ) (quad ζ)
          (starRingEnd ℂ).injective ξ
        rwa [quad_map_conj] at key
      have hqinv : ∀ ξ, (quad ζ).count ξ⁻¹ = (quad ζ).count ξ := by
        intro ξ
        have key := Multiset.count_map_eq_count' (fun x : ℂ => x⁻¹) (quad ζ) inv_injective ξ
        rwa [quad_map_inv] at key
      have h0' : (0 : ℂ) ∉ S - quad ζ :=
        fun h => h0 (Multiset.mem_of_le (Multiset.sub_le_self S (quad ζ)) h)
      have hconj' : ∀ ξ, (S - quad ζ).count ((starRingEnd ℂ) ξ) = (S - quad ζ).count ξ := by
        intro ξ; rw [Multiset.count_sub, Multiset.count_sub, hconj, hqconj]
      have hinv' : ∀ ξ, (S - quad ζ).count ξ⁻¹ = (S - quad ζ).count ξ := by
        intro ξ; rw [Multiset.count_sub, Multiset.count_sub, hinv, hqinv]
      have hRC' : (S - quad ζ).filter AxisP = {(-1 : ℂ), -1} := by
        rw [Multiset.filter_sub, hRC, quad_filter_eq_zero hoff, Multiset.sub_zero]
      -- (4) recurse.
      obtain ⟨S₀', hinvS₀', hsplit'⟩ := ih (S - quad ζ) hlt h0' hconj' hinv' hRC'
      -- (5) assemble the witness `S₀ := ζ ::ₘ ζ⁻¹ ::ₘ S₀'`.
      refine ⟨ζ ::ₘ ζ⁻¹ ::ₘ S₀', ?_, ?_⟩
      · rw [Multiset.map_cons, Multiset.map_cons, hinvS₀', inv_inv]
        exact Multiset.cons_swap _ _ _
      · rw [Multiset.map_cons, Multiset.map_cons, map_inv₀]
        have hq : quad ζ + (S₀' + S₀'.map (starRingEnd ℂ)) = S := by
          rw [← hsplit', add_comm, Multiset.sub_add_cancel hqle]
        rw [← hq]
        unfold quad
        simp only [Multiset.insert_eq_cons]
        refine Multiset.ext.mpr (fun a => ?_)
        simp only [Multiset.count_add, Multiset.count_cons, Multiset.count_singleton]
        omega
    · -- Case NO: every element is on-axis, so S = {-1, -1}.
      push_neg at hex
      have hfs : S.filter AxisP = S := Multiset.filter_eq_self.mpr hex
      rw [hfs] at hRC
      refine ⟨{(-1 : ℂ)}, ?_, ?_⟩
      · rw [Multiset.map_singleton]; norm_num
      · rw [hRC, Multiset.map_singleton]
        simp only [map_neg, map_one]
        rfl

/-! ### The decomposition: map form (frozen interface) -/

open Classical in
/-- **Decomposition lemma.** Let `S : Multiset ℂ` avoid `0`, be closed under both
conjugation (`starRingEnd ℂ`) and inversion (`(·⁻¹)`) as multiset maps, and have
real-or-unit-circle part exactly `{-1, -1}`. Then there is an inversion-closed
`S₀ : Multiset ℂ` with `S = S₀ + S₀.map (starRingEnd ℂ)`. (Fejér–Riesz root selection;
applied downstream to `(qtilde P).roots`.)

The `hRC` hypothesis uses the structural `instDecidableOr` instance (with
`Real.decidableEq`) — exactly the instance synthesised at `(qtilde P).roots.filter`
downstream. (`open Classical` here only supplies decidability for the *internal*
`AxisP` filter; the `hRC` argument's instance is unaffected.) It is bridged to the
classical `AxisP` filter via `convert … using 2`. -/
theorem exists_conj_split (S : Multiset ℂ)
    (h0 : (0 : ℂ) ∉ S)
    (hconj : S.map (starRingEnd ℂ) = S)
    (hinv : S.map (·⁻¹) = S)
    (hRC : S.filter (fun ζ => ζ.im = 0 ∨ ‖ζ‖ = 1) = {(-1 : ℂ), -1}) :
    ∃ S₀ : Multiset ℂ, S₀.map (·⁻¹) = S₀ ∧ S = S₀ + S₀.map (starRingEnd ℂ) := by
  -- align the `DecidablePred` instance of `hRC` with the one used by `AxisP`'s filter.
  have hRC' : S.filter AxisP = {(-1 : ℂ), -1} := by convert hRC using 2
  refine exists_conj_split_aux S h0 (fun ζ => ?_) (fun ζ => ?_) hRC'
  · have key := Multiset.count_map_eq_count' (starRingEnd ℂ) S (starRingEnd ℂ).injective ζ
    rwa [hconj] at key
  · have key := Multiset.count_map_eq_count' (fun x : ℂ => x⁻¹) S inv_injective ζ
    rwa [hinv] at key

end QAOA.IsingChain.Achievability
